<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5331ba30-3ce1-4838-be4a-b6c462501f0e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[decision gets extractionSuccess ;
add "Data Extraction Successful." to the messages of decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
