<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check vendor name</name>
  <uuid>6151f592-6ed7-45e2-bb6b-273bb993bea3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the vendor name of 'Vendor information' is empty 
then
	add "Vendor Name missing" to the msgs of decision ;
    add false to the outputs of decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
