<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check vendor phone no</name>
  <uuid>c0d1368c-cdd2-45f9-969e-28131c5c3b75</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the vendor phone number of 'Vendor information' is empty
then
	add "Vendor phone number missing" to the msgs of decision ;
    add false to the outputs of decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
