<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check vendor email</name>
  <uuid>3332c5cb-afe2-46df-9bb5-db8c98567e22</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the vendor email of 'Vendor information' is empty 
then
	add "Vendor email missing" to the msgs of decision ;
    add false to the outputs of decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
