<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0f17ca2c-eb5f-4104-bd9a-7990c8b7de51</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add true to the outputs of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
