<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>test</name>
  <uuid>0703503c-dcc5-415c-baa8-6008740934b7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is "Hello"
then
	set decision to "Hi";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
