<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>3b9dc18b-0355-4d68-86d0-ed5d1cc10cec</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set TicketDetails to "newuser" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
