<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>d4db56fe-9dd8-4830-912e-dedc29356937</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set itemtype to "createactive" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
