<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>80d6f8d8-42da-4c98-b3c6-334d4fccc9a4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set Input to "Hello";]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
