<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>0808721a-869b-4525-a5d9-646becd94cbe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set userstate to "active" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
