<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check inv date validity</name>
  <uuid>404f64a5-7bda-45c9-ad08-7fd865f3073d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the invoice date of 'Invoice detail' is not null 
    and the invoice date of 'Invoice detail' is after Today 
    then
	add "Invalid invoice date" to the msgs of decision ;
    add false to the outputs of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
