<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>inv number check</name>
  <uuid>c9dcf9fe-a599-471b-b6bd-0aca45e475c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the invoice number of 'Invoice detail' is empty
then
	add "Invoice number missing" to the msgs of decision ;
    add false to the outputs of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
