<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>inv total check</name>
  <uuid>7e46d9b9-a9a6-4841-8455-bc6d563e10bf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the invoice total of 'Invoice detail' is empty 
then
	add "Invoice total missing" to the msgs of decision ;
    add false to the outputs of decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
