<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f9e3246a-65f7-4080-a3ab-34f56cc74899</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add true to the outputs of decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
